In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
dataset=pd.read_csv("Tech_Layoff_Hiring_Trends.csv")

In [3]:
dataset.isnull().sum()

record_id                 0
company_name              0
industry                  0
country                   0
company_size              0
month                     0
year                      0
layoffs_count             0
layoff_percentage         0
reason_for_layoffs        0
ai_automation_impact      0
ai_replacement_risk       0
open_roles                0
hiring_trend              0
remote_jobs_percentage    0
top_hiring_role           0
stock_growth_percent      0
revenue_growth_percent    0
salary_budget_change      0
ai_adoption_level         0
employee_sentiment        0
job_security_score        0
market_condition          0
dtype: int64

In [4]:
dataset.shape

(12000, 23)

In [5]:
dataset.duplicated().sum()

0

In [6]:
dataset.dropna(how='all',inplace=True)

In [7]:
dataset.shape

(12000, 23)

In [8]:
from Univariate_1 import UnivariateClass
UC=UnivariateClass

In [9]:
qual=[]
quan=[]

In [10]:
qual,quan=UC.QualQuan(dataset)

In [11]:
qual

['record_id',
 'company_name',
 'industry',
 'country',
 'company_size',
 'month',
 'reason_for_layoffs',
 'hiring_trend',
 'top_hiring_role',
 'market_condition']

In [12]:
quan

['year',
 'layoffs_count',
 'layoff_percentage',
 'ai_automation_impact',
 'ai_replacement_risk',
 'open_roles',
 'remote_jobs_percentage',
 'stock_growth_percent',
 'revenue_growth_percent',
 'salary_budget_change',
 'ai_adoption_level',
 'employee_sentiment',
 'job_security_score']

In [13]:
descriptive=UC.Univariate_Table(dataset,quan)

In [14]:
lesser=[]
greater=[]

In [15]:
lesser,greater=UC.check_OutlierColumns(descriptive,quan)

In [16]:
lesser

['employee_sentiment', 'job_security_score']

In [17]:
greater

['layoffs_count', 'layoff_percentage', 'ai_automation_impact', 'open_roles']

In [18]:
UC.replace_Outlier(dataset,descriptive,lesser,greater)

In [19]:
dataset.describe()

,year,layoffs_count,layoff_percentage,ai_automation_impact,ai_replacement_risk,open_roles,remote_jobs_percentage,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score
count,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,2024.998750,4716.084208,12.673025,6.376979,7.208758,2881.511094,50.205150,22.466550,17.469175,5.920392,5.538750,6.497217,5.805654
std,0.817703,4471.400681,9.953661,3.544000,2.677148,2140.635208,23.299575,38.814405,24.359448,11.777264,2.583047,1.579421,1.647921
min,2024.000000,0.000000,0.000000,0.600000,1.000000,52.000000,10.000000,-45.000000,-25.000000,-28.000000,1.000000,2.100000,1.250000
25%,2024.000000,1369.500000,5.100000,3.500000,5.100000,1151.000000,29.800000,-11.200000,-3.500000,-2.700000,3.300000,5.400000,4.700000
50%,2025.000000,2733.000000,9.400000,5.900000,7.600000,2282.000000,50.500000,22.600000,17.500000,5.900000,5.600000,6.500000,5.900000
75%,2026.000000,6490.000000,17.300000,8.800000,10.000000,4432.250000,70.700000,55.700000,38.400000,14.600000,7.700000,7.600000,7.000000
max,2026.000000,14170.750000,35.600000,16.750000,10.000000,9354.125000,90.000000,90.000000,60.000000,38.200000,10.000000,10.000000,10.000000

In [20]:
descriptive

,year,layoffs_count,layoff_percentage,ai_automation_impact,ai_replacement_risk,open_roles,remote_jobs_percentage,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score
Mean,2024.99875,5009.572083,12.780125,6.376983,7.208758,2884.395,50.20515,22.46655,17.469175,5.920392,5.53875,6.496217,5.805033
Median,2025.0,2733.0,9.4,5.9,7.6,2282.0,50.5,22.6,17.5,5.9,5.6,6.5,5.9
Mode,2024,555,8.8,5.9,10.0,223,68.1,2.1,-15.7,-0.4,7.1,6.6,5.7
Q1:25%,2024.0,1369.5,5.1,3.5,5.1,1151.0,29.8,-11.2,-3.5,-2.7,3.3,5.4,4.7
Q2:50%,2025.0,2733.0,9.4,5.9,7.6,2282.0,50.5,22.6,17.5,5.9,5.6,6.5,5.9
Q3:75%,2026.0,6490.0,17.3,8.8,10.0,4432.25,70.7,55.7,38.4,14.6,7.7,7.6,7.0
99%,2026.0,19450.01,39.2,15.2,10.0,9311.04,89.2,88.5,59.2,30.401,9.9,9.8,9.1
Q4:100%,2026.0,19999.0,40.0,16.8,10.0,9997.0,90.0,90.0,60.0,38.2,10.0,10.0,10.0
IQR,2.0,5120.5,12.2,5.3,4.9,3281.25,40.9,66.9,41.9,17.3,4.4,2.2,2.3
1.5rule,3.0,7680.75,18.3,7.95,7.35,4921.875,61.35,100.35,62.85,25.95,6.6,3.3,3.45
Lesser,2021.0,-6311.25,-13.2,-4.45,-2.25,-3770.875,-31.55,-111.55,-66.35,-28.65,-3.3,2.1,1.25
Greater,2029.0,14170.75,35.6,16.75,17.35,9354.125,132.05,156.05,101.25,40.55,14.3,10.9,10.45
Min,2024,0,0.0,0.6,1.0,52,10.0,-45.0,-25.0,-28.0,1.0,1.3,1.0
Max,2026,19999,40.0,16.8,10.0,9997,90.0,90.0,60.0,38.2,10.0,10.0,10.0
kurtosis,-1.50442,0.866361,0.167609,-0.426055,-0.888516,0.333546,-1.232568,-1.194498,-1.190665,-0.606467,-1.179155,-0.34916,-0.244139
skew,0.0023,1.384624,1.047361,0.546627,-0.55631,0.895744,-0.01578,-0.000745,-0.003309,-0.002868,-0.026211,-0.133904,-0.337888
Variance,0.668637,26619000.672027,104.297446,12.560022,7.167121,4620848.549187,542.870183,1506.557999,593.382704,138.703955,6.672133,2.503851,2.721433
S.D,0.817703,5159.360491,10.212612,3.544012,2.677148,2149.615907,23.299575,38.814405,24.359448,11.777264,2.583047,1.582356,1.649677

In [21]:
dataset.columns

Index(['record_id', 'company_name', 'industry', 'country', 'company_size',
       'month', 'year', 'layoffs_count', 'layoff_percentage',
       'reason_for_layoffs', 'ai_automation_impact', 'ai_replacement_risk',
       'open_roles', 'hiring_trend', 'remote_jobs_percentage',
       'top_hiring_role', 'stock_growth_percent', 'revenue_growth_percent',
       'salary_budget_change', 'ai_adoption_level', 'employee_sentiment',
       'job_security_score', 'market_condition'],
      dtype='object')

In [22]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
dataset['market_condition_encoded'] = le.fit_transform(dataset['market_condition'])
print(dataset[['market_condition', 'market_condition_encoded']].head())

  market_condition  market_condition_encoded
0      Bull Market                         0
1      Bull Market                         0
2        Recession                         1
3        Recession                         1
4      Bull Market                         0

In [23]:
dataset

,record_id,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,...,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition,market_condition_encoded
0,T0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860.00,1.8,AI Automation,...,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market,0
1,T1,Palantir,AI,Canada,Big Tech,Feb,2024,955.00,1.8,Cost Cutting,...,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market,0
2,T2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,14170.75,9.5,Overhiring Correction,...,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession,1
3,T3,Spotify,Gaming,USA,Mid-size,Jun,2025,14170.75,9.1,Cost Cutting,...,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession,1
4,T4,Uber,Gaming,UK,Startup,Feb,2025,815.00,3.3,Market Slowdown,...,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,T11995,Anthropic,Gaming,USA,Enterprise,Mar,2024,766.00,8.4,Market Slowdown,...,15.8,Software Engineer,18.5,-16.8,-0.8,4.0,6.7,5.1,Bull Market,0
11996,T11996,Intel,Cybersecurity,Canada,Mid-size,Jul,2026,3407.00,13.9,Restructuring,...,51.8,Cloud Engineer,75.3,9.7,-1.7,2.3,7.7,6.2,Stable,2
11997,T11997,Netflix,Social Media,USA,Big Tech,Sep,2025,2576.00,8.7,Market Slowdown,...,88.8,DevOps Engineer,40.9,11.1,10.7,7.0,8.0,5.1,Recession,1
11998,T11998,Salesforce,Gaming,Germany,Big Tech,Sep,2025,1039.00,9.1,Overhiring Correction,...,37.6,Cybersecurity Analyst,24.2,44.2,27.4,8.9,7.3,6.2,Bull Market,0
11999,T11999,Databricks,AI,Germany,Big Tech,Mar,2026,493.00,6.6,Restructuring,...,32.6,ML Engineer,45.1,-9.3,-7.2,2.9,4.9,6.0,Bull Market,0

In [24]:
dataset['market_condition_encoded'].unique()

array([0, 1, 2])

In [25]:
dataset[['market_condition','market_condition_encoded']].drop_duplicates()

   market_condition  market_condition_encoded
0       Bull Market                         0
2         Recession                         1
26           Stable                         2

In [26]:
print(dict(zip(le.classes_, le.transform(le.classes_))))

{'Bull Market': 0, 'Recession': 1, 'Stable': 2}

In [27]:
X = dataset.drop(['market_condition','market_condition_encoded'], axis=1)
y = dataset['market_condition_encoded']

In [28]:
X

,record_id,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,...,open_roles,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score
0,T0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860.00,1.8,AI Automation,...,5426.000,Moderate Hiring,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6
1,T1,Palantir,AI,Canada,Big Tech,Feb,2024,955.00,1.8,Cost Cutting,...,9354.125,Moderate Hiring,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2
2,T2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,14170.75,9.5,Overhiring Correction,...,437.000,Hiring Freeze,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9
3,T3,Spotify,Gaming,USA,Mid-size,Jun,2025,14170.75,9.1,Cost Cutting,...,1075.000,Hiring Freeze,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7
4,T4,Uber,Gaming,UK,Startup,Feb,2025,815.00,3.3,Market Slowdown,...,537.000,Moderate Hiring,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,T11995,Anthropic,Gaming,USA,Enterprise,Mar,2024,766.00,8.4,Market Slowdown,...,5364.000,Moderate Hiring,15.8,Software Engineer,18.5,-16.8,-0.8,4.0,6.7,5.1
11996,T11996,Intel,Cybersecurity,Canada,Mid-size,Jul,2026,3407.00,13.9,Restructuring,...,3865.000,Hiring Freeze,51.8,Cloud Engineer,75.3,9.7,-1.7,2.3,7.7,6.2
11997,T11997,Netflix,Social Media,USA,Big Tech,Sep,2025,2576.00,8.7,Market Slowdown,...,544.000,Moderate Hiring,88.8,DevOps Engineer,40.9,11.1,10.7,7.0,8.0,5.1
11998,T11998,Salesforce,Gaming,Germany,Big Tech,Sep,2025,1039.00,9.1,Overhiring Correction,...,2243.000,Moderate Hiring,37.6,Cybersecurity Analyst,24.2,44.2,27.4,8.9,7.3,6.2
11999,T11999,Databricks,AI,Germany,Big Tech,Mar,2026,493.00,6.6,Restructuring,...,6987.000,Moderate Hiring,32.6,ML Engineer,45.1,-9.3,-7.2,2.9,4.9,6.0

In [29]:
y

0        0
1        0
2        1
3        1
4        0
        ..
11995    0
11996    2
11997    1
11998    0
11999    0
Name: market_condition_encoded, Length: 12000, dtype: int32

In [30]:
dataset.head()

,record_id,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,...,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition,market_condition_encoded
0,T0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860.00,1.8,AI Automation,...,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market,0
1,T1,Palantir,AI,Canada,Big Tech,Feb,2024,955.00,1.8,Cost Cutting,...,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market,0
2,T2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,14170.75,9.5,Overhiring Correction,...,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession,1
3,T3,Spotify,Gaming,USA,Mid-size,Jun,2025,14170.75,9.1,Cost Cutting,...,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession,1
4,T4,Uber,Gaming,UK,Startup,Feb,2025,815.00,3.3,Market Slowdown,...,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market,0

In [31]:
dataset['top_hiring_role_encoded'] = le.fit_transform(dataset['top_hiring_role'])
dataset['company_size_encoded']=le.fit_transform(dataset['company_size'])

In [32]:
dataset['top_hiring_role_encoded']

0        5
1        5
2        4
3        4
4        4
        ..
11995    7
11996    0
11997    3
11998    1
11999    5
Name: top_hiring_role_encoded, Length: 12000, dtype: int32

In [33]:
dataset['company_size_encoded']

0        1
1        0
2        2
3        2
4        3
        ..
11995    1
11996    2
11997    0
11998    0
11999    0
Name: company_size_encoded, Length: 12000, dtype: int32

In [34]:
dataset.drop(['top_hiring_role','company_size'],axis=1)

,record_id,company_name,industry,country,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,ai_automation_impact,...,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition,market_condition_encoded,top_hiring_role_encoded,company_size_encoded
0,T0,Microsoft,AI,Singapore,Mar,2026,860.00,1.8,AI Automation,6.4,...,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market,0,5,1
1,T1,Palantir,AI,Canada,Feb,2024,955.00,1.8,Cost Cutting,0.9,...,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market,0,5,0
2,T2,Anthropic,Cybersecurity,USA,Apr,2025,14170.75,9.5,Overhiring Correction,7.1,...,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession,1,4,2
3,T3,Spotify,Gaming,USA,Jun,2025,14170.75,9.1,Cost Cutting,10.4,...,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession,1,4,2
4,T4,Uber,Gaming,UK,Feb,2025,815.00,3.3,Market Slowdown,11.4,...,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market,0,4,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,T11995,Anthropic,Gaming,USA,Mar,2024,766.00,8.4,Market Slowdown,5.6,...,18.5,-16.8,-0.8,4.0,6.7,5.1,Bull Market,0,7,1
11996,T11996,Intel,Cybersecurity,Canada,Jul,2026,3407.00,13.9,Restructuring,3.4,...,75.3,9.7,-1.7,2.3,7.7,6.2,Stable,2,0,2
11997,T11997,Netflix,Social Media,USA,Sep,2025,2576.00,8.7,Market Slowdown,8.3,...,40.9,11.1,10.7,7.0,8.0,5.1,Recession,1,3,0
11998,T11998,Salesforce,Gaming,Germany,Sep,2025,1039.00,9.1,Overhiring Correction,9.1,...,24.2,44.2,27.4,8.9,7.3,6.2,Bull Market,0,1,0
11999,T11999,Databricks,AI,Germany,Mar,2026,493.00,6.6,Restructuring,2.4,...,45.1,-9.3,-7.2,2.9,4.9,6.0,Bull Market,0,5,0

In [35]:
dataset.columns

Index(['record_id', 'company_name', 'industry', 'country', 'company_size',
       'month', 'year', 'layoffs_count', 'layoff_percentage',
       'reason_for_layoffs', 'ai_automation_impact', 'ai_replacement_risk',
       'open_roles', 'hiring_trend', 'remote_jobs_percentage',
       'top_hiring_role', 'stock_growth_percent', 'revenue_growth_percent',
       'salary_budget_change', 'ai_adoption_level', 'employee_sentiment',
       'job_security_score', 'market_condition', 'market_condition_encoded',
       'top_hiring_role_encoded', 'company_size_encoded'],
      dtype='object')

In [36]:
dataset=pd.get_dummies(dataset[['record_id', 'company_name', 'industry', 'country', 'company_size',
       'month', 'year', 'layoffs_count', 'layoff_percentage',
       'reason_for_layoffs', 'ai_automation_impact', 'ai_replacement_risk',
       'open_roles', 'hiring_trend', 'remote_jobs_percentage',
       'top_hiring_role', 'stock_growth_percent', 'revenue_growth_percent',
       'salary_budget_change', 'ai_adoption_level', 'employee_sentiment',
       'job_security_score']],drop_first=True).astype(float)

In [37]:
dataset

,year,layoffs_count,layoff_percentage,ai_automation_impact,ai_replacement_risk,open_roles,remote_jobs_percentage,stock_growth_percent,revenue_growth_percent,salary_budget_change,...,hiring_trend_Downsizing,hiring_trend_Hiring Freeze,hiring_trend_Moderate Hiring,top_hiring_role_Cybersecurity Analyst,top_hiring_role_Data Scientist,top_hiring_role_DevOps Engineer,top_hiring_role_Frontend Developer,top_hiring_role_ML Engineer,top_hiring_role_Product Manager,top_hiring_role_Software Engineer
0,2026.0,860.00,1.8,6.4,5.0,5426.000,46.7,-25.7,30.3,4.9,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,2024.0,955.00,1.8,0.9,1.1,9354.125,58.9,-5.6,6.1,1.5,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2025.0,14170.75,9.5,7.1,3.9,437.000,85.4,7.0,-23.6,-14.9,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,2025.0,14170.75,9.1,10.4,7.4,1075.000,44.0,31.6,-22.3,-1.6,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,2025.0,815.00,3.3,11.4,10.0,537.000,53.2,85.3,26.6,9.8,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,2024.0,766.00,8.4,5.6,5.3,5364.000,15.8,18.5,-16.8,-0.8,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
11996,2026.0,3407.00,13.9,3.4,5.7,3865.000,51.8,75.3,9.7,-1.7,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11997,2025.0,2576.00,8.7,8.3,8.7,544.000,88.8,40.9,11.1,10.7,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
11998,2025.0,1039.00,9.1,9.1,10.0,2243.000,37.6,24.2,44.2,27.4,...,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
11999,2026.0,493.00,6.6,2.4,3.2,6987.000,32.6,45.1,-9.3,-7.2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0