In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest,f_classif

In [2]:
dataset = pd.read_csv("Tech_Layoff_Hiring_Trends.csv")

In [3]:
dataset.columns

Index(['record_id', 'company_name', 'industry', 'country', 'company_size',
       'month', 'year', 'layoffs_count', 'layoff_percentage',
       'reason_for_layoffs', 'ai_automation_impact', 'ai_replacement_risk',
       'open_roles', 'hiring_trend', 'remote_jobs_percentage',
       'top_hiring_role', 'stock_growth_percent', 'revenue_growth_percent',
       'salary_budget_change', 'ai_adoption_level', 'employee_sentiment',
       'job_security_score', 'market_condition'],
      dtype='object')

In [4]:
dataset

,record_id,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,...,hiring_trend,remote_jobs_percentage,top_hiring_role,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition
0,T0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860,1.8,AI Automation,...,Moderate Hiring,46.7,ML Engineer,-25.7,30.3,4.9,4.4,8.7,8.6,Bull Market
1,T1,Palantir,AI,Canada,Big Tech,Feb,2024,955,1.8,Cost Cutting,...,Moderate Hiring,58.9,ML Engineer,-5.6,6.1,1.5,1.0,8.2,7.2,Bull Market
2,T2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,18912,9.5,Overhiring Correction,...,Hiring Freeze,85.4,Frontend Developer,7.0,-23.6,-14.9,5.6,4.5,5.9,Recession
3,T3,Spotify,Gaming,USA,Mid-size,Jun,2025,18159,9.1,Cost Cutting,...,Hiring Freeze,44.0,Frontend Developer,31.6,-22.3,-1.6,6.5,5.4,4.7,Recession
4,T4,Uber,Gaming,UK,Startup,Feb,2025,815,3.3,Market Slowdown,...,Moderate Hiring,53.2,Frontend Developer,85.3,26.6,9.8,9.3,6.7,5.8,Bull Market
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,T11995,Anthropic,Gaming,USA,Enterprise,Mar,2024,766,8.4,Market Slowdown,...,Moderate Hiring,15.8,Software Engineer,18.5,-16.8,-0.8,4.0,6.7,5.1,Bull Market
11996,T11996,Intel,Cybersecurity,Canada,Mid-size,Jul,2026,3407,13.9,Restructuring,...,Hiring Freeze,51.8,Cloud Engineer,75.3,9.7,-1.7,2.3,7.7,6.2,Stable
11997,T11997,Netflix,Social Media,USA,Big Tech,Sep,2025,2576,8.7,Market Slowdown,...,Moderate Hiring,88.8,DevOps Engineer,40.9,11.1,10.7,7.0,8.0,5.1,Recession
11998,T11998,Salesforce,Gaming,Germany,Big Tech,Sep,2025,1039,9.1,Overhiring Correction,...,Moderate Hiring,37.6,Cybersecurity Analyst,24.2,44.2,27.4,8.9,7.3,6.2,Bull Market
11999,T11999,Databricks,AI,Germany,Big Tech,Mar,2026,493,6.6,Restructuring,...,Moderate Hiring,32.6,ML Engineer,45.1,-9.3,-7.2,2.9,4.9,6.0,Bull Market

In [5]:
dataset.isnull().sum()

record_id                 0
company_name              0
industry                  0
country                   0
company_size              0
month                     0
year                      0
layoffs_count             0
layoff_percentage         0
reason_for_layoffs        0
ai_automation_impact      0
ai_replacement_risk       0
open_roles                0
hiring_trend              0
remote_jobs_percentage    0
top_hiring_role           0
stock_growth_percent      0
revenue_growth_percent    0
salary_budget_change      0
ai_adoption_level         0
employee_sentiment        0
job_security_score        0
market_condition          0
dtype: int64

In [6]:
def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=f_classif, k=n)
        
        #selected_features = X.columns[mask].tolist()
        #print(test.get_params
        
        fit1= test.fit(indep_X,dep_Y)
        selectk_features = fit1.transform(indep_X)
        mask=test.get_support()
        selected_features = indep_X.columns[mask].tolist()
        print(selected_features)
        return selectk_features

In [7]:
dataset.drop("record_id",axis=1,inplace=True)

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['market_condition'] = le.fit_transform(dataset['market_condition'])

In [9]:
dataset = pd.get_dummies(
    dataset,
    columns=['hiring_trend'],
    drop_first=True,dtype=int
)

In [10]:
dataset

,company_name,industry,country,company_size,month,year,layoffs_count,layoff_percentage,reason_for_layoffs,ai_automation_impact,...,stock_growth_percent,revenue_growth_percent,salary_budget_change,ai_adoption_level,employee_sentiment,job_security_score,market_condition,hiring_trend_Downsizing,hiring_trend_Hiring Freeze,hiring_trend_Moderate Hiring
0,Microsoft,AI,Singapore,Enterprise,Mar,2026,860,1.8,AI Automation,6.4,...,-25.7,30.3,4.9,4.4,8.7,8.6,0,0,0,1
1,Palantir,AI,Canada,Big Tech,Feb,2024,955,1.8,Cost Cutting,0.9,...,-5.6,6.1,1.5,1.0,8.2,7.2,0,0,0,1
2,Anthropic,Cybersecurity,USA,Mid-size,Apr,2025,18912,9.5,Overhiring Correction,7.1,...,7.0,-23.6,-14.9,5.6,4.5,5.9,1,0,1,0
3,Spotify,Gaming,USA,Mid-size,Jun,2025,18159,9.1,Cost Cutting,10.4,...,31.6,-22.3,-1.6,6.5,5.4,4.7,1,0,1,0
4,Uber,Gaming,UK,Startup,Feb,2025,815,3.3,Market Slowdown,11.4,...,85.3,26.6,9.8,9.3,6.7,5.8,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,Anthropic,Gaming,USA,Enterprise,Mar,2024,766,8.4,Market Slowdown,5.6,...,18.5,-16.8,-0.8,4.0,6.7,5.1,0,0,0,1
11996,Intel,Cybersecurity,Canada,Mid-size,Jul,2026,3407,13.9,Restructuring,3.4,...,75.3,9.7,-1.7,2.3,7.7,6.2,2,0,1,0
11997,Netflix,Social Media,USA,Big Tech,Sep,2025,2576,8.7,Market Slowdown,8.3,...,40.9,11.1,10.7,7.0,8.0,5.1,1,0,0,1
11998,Salesforce,Gaming,Germany,Big Tech,Sep,2025,1039,9.1,Overhiring Correction,9.1,...,24.2,44.2,27.4,8.9,7.3,6.2,0,0,0,1
11999,Databricks,AI,Germany,Big Tech,Mar,2026,493,6.6,Restructuring,2.4,...,45.1,-9.3,-7.2,2.9,4.9,6.0,0,0,0,1

In [11]:
indep_X=dataset[['layoffs_count',
                'layoff_percentage',
                'job_security_score',
                'hiring_trend_Downsizing',
                'hiring_trend_Moderate Hiring']]

In [12]:
indep_X

,layoffs_count,layoff_percentage,job_security_score,hiring_trend_Downsizing,hiring_trend_Moderate Hiring
0,860,1.8,8.6,0,1
1,955,1.8,7.2,0,1
2,18912,9.5,5.9,0,0
3,18159,9.1,4.7,0,0
4,815,3.3,5.8,0,1
...,...,...,...,...,...
11995,766,8.4,5.1,0,1
11996,3407,13.9,6.2,0,0
11997,2576,8.7,5.1,0,1
11998,1039,9.1,6.2,0,1
11999,493,6.6,6.0,0,1

In [13]:
dep_Y=dataset['market_condition']

In [ ]:
dep_Y

In [14]:
dataset['market_condition'].value_counts()

2    4078
0    4019
1    3903
Name: market_condition, dtype: int64

In [15]:
dep_Y

0        0
1        0
2        1
3        1
4        0
        ..
11995    0
11996    2
11997    1
11998    0
11999    0
Name: market_condition, Length: 12000, dtype: int32

In [16]:
kbest=selectkbest(indep_X,dep_Y,5)

['layoffs_count', 'layoff_percentage', 'job_security_score', 'hiring_trend_Downsizing', 'hiring_trend_Moderate Hiring']

In [17]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 1/3, random_state = 0)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [20]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt'],
              'n_estimators':[10,100]} 
grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_macro') 

grid.fit(X_train_, y_train)

C:\Anaconda3\envs\web\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 16 concurrent workers.

Fitting 3 folds for each of 8 candidates, totalling 24 fits

[Parallel(n_jobs=-1)]: Done   2 out of  24 | elapsed:    4.3s remaining:   48.6s
[Parallel(n_jobs=-1)]: Done  11 out of  24 | elapsed:    4.6s remaining:    5.5s
[Parallel(n_jobs=-1)]: Done  20 out of  24 | elapsed:    5.9s remaining:    1.1s
[Parallel(n_jobs=-1)]: Done  24 out of  24 | elapsed:    6.1s finished
C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt'],
                         'n_estimators': [10, 100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1_macro', verbose=3)

In [21]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}

In [22]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [37]:
print(grid.predict(X_test))

[1 1 1 ... 1 1 1]

C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [39]:
pred = grid.predict(X_test)
print(np.unique(pred))

[1]

C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):

In [23]:
table=pd.DataFrame.from_dict(re)

In [24]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.157868,0.018880,0.030436,0.008026,gini,auto,10,"{'criterion': 'gini', 'max_features': 'auto', ...",0.869073,0.883153,0.877232,0.876484,0.005773,7
1,1.140186,0.009702,0.080524,0.001795,gini,auto,100,"{'criterion': 'gini', 'max_features': 'auto', ...",0.886303,0.891760,0.883318,0.887127,0.003495,2
2,0.137293,0.008553,0.016545,0.002496,gini,sqrt,10,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.877502,0.887395,0.874922,0.879939,0.005376,5
3,1.131693,0.005273,0.078381,0.004115,gini,sqrt,100,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.885681,0.889559,0.885032,0.886757,0.001999,4
4,0.155948,0.005653,0.014600,0.001101,entropy,auto,10,"{'criterion': 'entropy', 'max_features': 'auto...",0.875179,0.875389,0.877074,0.875881,0.000848,8
5,1.424814,0.022739,0.080759,0.002886,entropy,auto,100,"{'criterion': 'entropy', 'max_features': 'auto...",0.885955,0.891117,0.883322,0.886798,0.003237,3
6,0.156095,0.005457,0.014189,0.000827,entropy,sqrt,10,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.877977,0.883372,0.877249,0.879532,0.002731,6
7,1.403126,0.020151,0.083044,0.001247,entropy,sqrt,100,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.887231,0.891021,0.886224,0.888158,0.002065,1

In [25]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}: 0.8987215608195633

In [26]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[1283    0   35]
 [   7 1240  108]
 [ 234   20 1073]]

In [27]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.84      0.97      0.90      1318
           1       0.98      0.92      0.95      1355
           2       0.88      0.81      0.84      1327

    accuracy                           0.90      4000
   macro avg       0.90      0.90      0.90      4000
weighted avg       0.90      0.90      0.90      4000

In [36]:
import pickle
filename='rf_final_model.sav'
pickle.dump(grid,open(filename,'wb'))
loaded_model=pickle.load(open(filename,'rb'))

layoffs_count=float(input("Layoffs Count: "))
layoff_percentage=float(input("layoff_percentage:"))
job_security_score=float(input("job_security_score:"))
hiring_trend_Downsizing=float(input("hiring_trend_Downsizing:"))
hiring_trend_Moderate_Hiring=float(input("hiring_trend_Moderate Hiring:"))

prediction=loaded_model.predict([[layoffs_count,
                layoff_percentage,
                job_security_score,
                hiring_trend_Downsizing,
                hiring_trend_Moderate_Hiring]])
print("\n Prediction : 0 - Bull Market")
print("\n              1 - Recession")
print("\n              2 - Stable")

print("\n Prediction : ",prediction[0])

Layoffs Count: 3407
layoff_percentage:13.9
job_security_score:6.2
hiring_trend_Downsizing:0
hiring_trend_Moderate Hiring:0

 Prediction : 0 - Bull Market

              1 - Recession

              2 - Stable

 Prediction :  1

C:\Anaconda3\envs\web\lib\site-packages\sklearn\utils\fixes.py:230: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if _joblib.__version__ >= LooseVersion('0.12'):